<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3n74sv4\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3n74sv4/appProdProjectContainer.php') {
    touch(__DIR__.'/Container3n74sv4.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container3n74sv4\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container3n74sv4\appProdProjectContainer([
    'container.build_hash' => '3n74sv4',
    'container.build_id' => '22cc27ca',
    'container.build_time' => 1720454208,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3n74sv4');
